[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solanapdas = "Dk6jEcX41441XG58ifP25zBVwPTvhbe4Rhc8pZpxVzbM"

[programs.localnet]
solanapdas = "Dk6jEcX41441XG58ifP25zBVwPTvhbe4Rhc8pZpxVzbM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# wallet = "~/.config/solana/id.json"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
